### ISSUE TITLE
Another option Palemoon 32bit Browser

### ISSUE THREAD

**Issue by nconder** [Kris-Sekula/UCS-KVM#1]
Thanks for this jlnp file!

Another option is the old Palemoon 32bit browser if you need access to CIMC via web.
https://www.palemoon.org/download.shtml

**Comment by Kris-Sekula** [comment]
Correct, palemoon can be used but you also need a correct version of flash (if I remember correctly if you use the new version of flash even with palemoon it will not work). The advantage of the jnlp files is that you can keep them in a folder and use them as "quick links" to all of your servers. In my experience 99% of the time I needed to access a server was to view the KVM, with the jnlp file you don't have to log in and navigate to the KVM console, you just double click and you get connected directly to your servers KVM :)
