### ISSUE TITLE
java won't start

### ISSUE THREAD

**Issue by wlang1505** [Kris-Sekula/UCS-KVM#3]
Hi, I upgraded the C220M3 CIMC to version 3.0.4s. Since that I'm not able to launch the KVM console in CIMC. I found our script.
But when executing the jnlp file it stops with a failure:

Server returned HTTP response code: 403 for URL
https://192.168.10.241:443/software/avctNuova.jar.pack.gz

**Comment by Kris-Sekula** [comment]
I don't have a box to test anymore, but 403 is "forbidden" ... I would
double check if the credentials you put into the the config are correct (I
would ssh to the CIMC with the same credentials to double check),
Another thing you can try is to start the Java control panel and
somewhere there should be a "security" section, you may have to add
exception to the list for the ip address of you CIMC

**Comment by wlang1505** [comment]
Hi Kris,

Many thanks for your quick response. I have done both as you suggested. But it didn’t help.
I can provide you access to it if you want to take a look at.
Maybe you have other ideas as well

Many thanks, Wolfgang

From: Kris Sekula ***@***.***>
Reply to: Kris-Sekula/UCS-KVM ***@***.***>
Date: Tuesday, 17. May 2022 at 18:07
To: Kris-Sekula/UCS-KVM ***@***.***>
Cc: Wolfgang Lang ***@***.***>, Author ***@***.***>
Subject: Re: [Kris-Sekula/UCS-KVM] java won't start (Issue #3)

I don't have a box to test anymore, but 403 is "forbidden" ... I would
double check if the credentials you put into the the config are correct (I
would ssh to the CIMC with the same credentials to double check),
Another thing you can try is to start the Java control panel and
somewhere there should be a "security" section, you may have to add
exception to the list for the ip address of you CIMC

**Comment by spectrumitec** [comment]
Hi all, the 403 error is related to the SSL certificate. Probably need to create a trusted certificate for Java. 

You can bypass SSL by disabling it on the CIMC. SSH to CIMC and change scope for http:

scope http
set http-redirect no
commit

Change the KVM script to use http:// and not https://. Remove :443 from the script also.
